server:
  port: 10087
spring:
  application:
    name: junit-order-service
  datasource:
    url: jdbc:mysql://123.56.117.108:3306/junit?serverTimezone=GMT%2B8&allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&useSSL=false&requireSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: 123456
  cloud:
    sentinel:
      transport:
        dashboard: localhost:8080
        port: 8719
      eager: true
      datasource:
        # 流控
        flow:
          nacos:
            server-addr: localhost:8848
            dataId: ${spring.application.name}-flow-rules
            groupId: SENTINEL_GROUP
            rule-type: flow
        # 降级
        degrade:
          nacos:
            server-addr: localhost:8848
            dataId: ${spring.application.name}-degrade-rules
            groupId: SENTINEL_GROUP
            rule-type: degrade
feign:
  sentinel:
    enabled: true
  client:
    config:
      default:
        connect-timeout: 3000
        read-timeout: 3000
        logger-level: full
management:
  endpoints:
    web:
      exposure:
        include: '*'
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl