server:
  port: 10087
spring:
  datasource:
    url: jdbc:mysql://123.56.117.108:3306/junit?serverTimezone=GMT%2B8&allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&useSSL=false&requireSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: 123456
